ERROR 2025-08-04 11:15:38,753 log 20220 7216 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 28, in validate
    serializer = UserProfileSerializer(self.user.profile)
                                       ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
ERROR 2025-08-04 11:15:38,760 basehttp 20220 7216 "POST /api/token/ HTTP/1.1" 500 121858
ERROR 2025-08-04 12:50:50,075 log 3272 10648 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 28, in validate
    serializer = UserProfileSerializer(self.user.profile)
                                       ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
ERROR 2025-08-04 12:50:50,079 basehttp 3272 10648 "POST /api/token/ HTTP/1.1" 500 121858
ERROR 2025-08-04 12:51:01,510 log 3272 10648 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 28, in validate
    serializer = UserProfileSerializer(self.user.profile)
                                       ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
ERROR 2025-08-04 12:51:01,514 basehttp 3272 10648 "POST /api/token/ HTTP/1.1" 500 121858
ERROR 2025-08-04 13:03:07,142 log 21076 3012 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 28, in validate
    serializer = UserProfileSerializer(self.user.profile)
                                       ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
ERROR 2025-08-04 13:03:07,148 basehttp 21076 3012 "POST /api/token/ HTTP/1.1" 500 121892
ERROR 2025-08-04 13:03:16,433 log 21076 3012 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 28, in validate
    serializer = UserProfileSerializer(self.user.profile)
                                       ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
ERROR 2025-08-04 13:03:16,437 basehttp 21076 3012 "POST /api/token/ HTTP/1.1" 500 121892
ERROR 2025-08-04 13:03:20,587 log 21076 3012 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 28, in validate
    serializer = UserProfileSerializer(self.user.profile)
                                       ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
ERROR 2025-08-04 13:03:20,590 basehttp 21076 3012 "POST /api/token/ HTTP/1.1" 500 121892
ERROR 2025-08-04 13:04:24,620 log 9284 9716 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 28, in validate
    serializer = UserProfileSerializer(self.user.profile)
                                       ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
ERROR 2025-08-04 13:04:24,623 basehttp 9284 9716 "POST /api/token/ HTTP/1.1" 500 121892
ERROR 2025-08-04 13:26:46,542 log 13620 6056 Internal Server Error: /api/register/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 44, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\serializers.py", line 58, in create
    user = User.objects.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\models.py", line 68, in create_user_profile
    Profile.objects.create(user=instance)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\models.py", line 56, in save
    self.full_clean()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1679, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'department': ['A Department must be assigned for Faculty and HOD roles.']}
ERROR 2025-08-04 13:26:46,548 basehttp 13620 6056 "POST /api/register/ HTTP/1.1" 500 178611
ERROR 2025-08-04 13:43:33,150 log 21276 20396 Internal Server Error: /api/register/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 44, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\serializers.py", line 53, in create
    user = User.objects.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\models.py", line 68, in create_user_profile
    Profile.objects.create(user=instance)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\models.py", line 56, in save
    self.full_clean()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1679, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'department': ['A Department must be assigned for Faculty and HOD roles.']}
ERROR 2025-08-04 13:43:33,155 basehttp 21276 20396 "POST /api/register/ HTTP/1.1" 500 178720
ERROR 2025-08-07 15:05:11,977 log 15472 384 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 29, in validate
    data['user'] = serializer.data
                   ^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 375, in fields
    fields[key] = value
    ~~~~~~^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 167, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\fields.py", line 358, in bind
    assert self.source != field_name, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: It is redundant to specify `source='full_name'` on field 'CharField' in serializer 'UserProfileSerializer', because it is the same as the field name. Remove the `source` keyword argument.
ERROR 2025-08-07 15:05:11,990 basehttp 15472 384 "POST /api/token/ HTTP/1.1" 500 153431
ERROR 2025-08-07 15:05:42,099 log 18068 18388 Internal Server Error: /api/token/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 29, in validate
    data['user'] = serializer.data
                   ^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 573, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 375, in fields
    fields[key] = value
    ~~~~~~^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 167, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\fields.py", line 358, in bind
    assert self.source != field_name, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: It is redundant to specify `source='full_name'` on field 'CharField' in serializer 'UserProfileSerializer', because it is the same as the field name. Remove the `source` keyword argument.
ERROR 2025-08-07 15:05:42,109 basehttp 18068 18388 "POST /api/token/ HTTP/1.1" 500 153431
ERROR 2025-08-12 14:46:50,367 log 13800 17584 Internal Server Error: /api/register/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 51, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\serializers.py", line 60, in create
    user = User.objects.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\models.py", line 83, in create_user_profile
    email_body = render_to_string('account_verification_email.txt', {
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: account_verification_email.txt
ERROR 2025-08-12 14:46:50,373 basehttp 13800 17584 "POST /api/register/ HTTP/1.1" 500 177264
ERROR 2025-08-12 19:00:06,282 log 17180 14900 Internal Server Error: /api/register/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 48, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\serializers.py", line 60, in create
    user = User.objects.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\models.py", line 84, in create_user_profile
    send_mail(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\__init__.py", line 92, in send_mail
    return mail.send()
           ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\gagan\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\gagan\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\gagan\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-241d1ef59b2sm302928505ad.7 - gsmtp')
ERROR 2025-08-12 19:00:06,290 basehttp 17180 14900 "POST /api/register/ HTTP/1.1" 500 201626
ERROR 2025-08-12 19:10:28,532 log 17180 23152 Internal Server Error: /api/register/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\views.py", line 48, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\serializers.py", line 60, in create
    user = User.objects.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1023, in save_base
    post_save.send(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\users\models.py", line 84, in create_user_profile
    send_mail(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\__init__.py", line 92, in send_mail
    return mail.send()
           ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\message.py", line 307, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\mail\backends\smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\gagan\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\gagan\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "C:\Users\gagan\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-b422bacbb74sm25305898a12.42 - gsmtp')
ERROR 2025-08-12 19:10:28,534 basehttp 17180 23152 "POST /api/register/ HTTP/1.1" 500 201635
ERROR 2025-08-22 20:15:29,271 log 12164 20624 Internal Server Error: /api/faculty/t3_2chapters/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "department_id" of relation "reports_t3_2chapterpublication" violates not-null constraint
DETAIL:  Failing row contains (1, 2025, Q1, 2025-08-22 14:45:29.041469+00, 2025-08-22 14:45:29.041469+00, ct1, Co-Author, pd2, issn1, , 2025, National, https://drive.google.com/file/d/19_StdCCOvbD3LqHP9ZpMFr5Oe3pCMDK..., null, 1).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\reports\serializers.py", line 29, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "department_id" of relation "reports_t3_2chapterpublication" violates not-null constraint
DETAIL:  Failing row contains (1, 2025, Q1, 2025-08-22 14:45:29.041469+00, 2025-08-22 14:45:29.041469+00, ct1, Co-Author, pd2, issn1, , 2025, National, https://drive.google.com/file/d/19_StdCCOvbD3LqHP9ZpMFr5Oe3pCMDK..., null, 1).

ERROR 2025-08-22 20:15:35,495 log 12164 5900 Internal Server Error: /api/faculty/t3_2chapters/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "department_id" of relation "reports_t3_2chapterpublication" violates not-null constraint
DETAIL:  Failing row contains (2, 2025, Q1, 2025-08-22 14:45:35.46037+00, 2025-08-22 14:45:35.46037+00, ct1, Co-Author, pd2, issn1, i1, 2025, National, https://drive.google.com/file/d/19_StdCCOvbD3LqHP9ZpMFr5Oe3pCMDK..., null, 1).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\reports\serializers.py", line 29, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "department_id" of relation "reports_t3_2chapterpublication" violates not-null constraint
DETAIL:  Failing row contains (2, 2025, Q1, 2025-08-22 14:45:35.46037+00, 2025-08-22 14:45:35.46037+00, ct1, Co-Author, pd2, issn1, i1, 2025, National, https://drive.google.com/file/d/19_StdCCOvbD3LqHP9ZpMFr5Oe3pCMDK..., null, 1).

ERROR 2025-08-22 20:15:45,488 log 12164 7212 Internal Server Error: /api/faculty/t3_2chapters/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "department_id" of relation "reports_t3_2chapterpublication" violates not-null constraint
DETAIL:  Failing row contains (3, 2024, Q1, 2025-08-22 14:45:45.450282+00, 2025-08-22 14:45:45.450282+00, ct1, Co-Author, pd2, issn1, i1, 2025, National, https://drive.google.com/file/d/19_StdCCOvbD3LqHP9ZpMFr5Oe3pCMDK..., null, 1).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\reports\serializers.py", line 29, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "department_id" of relation "reports_t3_2chapterpublication" violates not-null constraint
DETAIL:  Failing row contains (3, 2024, Q1, 2025-08-22 14:45:45.450282+00, 2025-08-22 14:45:45.450282+00, ct1, Co-Author, pd2, issn1, i1, 2025, National, https://drive.google.com/file/d/19_StdCCOvbD3LqHP9ZpMFr5Oe3pCMDK..., null, 1).

ERROR 2025-08-25 14:10:46,171 log Internal Server Error: /api/data/s2_1articles/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1193, in get_field_names
    assert field_name not in self._declared_fields, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot both declare the field 'faculty_name' and include it in the ReportSerializer 'exclude' option. Remove the field or, if inherited from a parent serializer, disable with `faculty_name = None`.
ERROR 2025-08-25 14:14:59,664 log Internal Server Error: /api/data/s2_1articles/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1193, in get_field_names
    assert field_name not in self._declared_fields, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot both declare the field 'department_name' and include it in the ReportSerializer 'exclude' option. Remove the field or, if inherited from a parent serializer, disable with `department_name = None`.
ERROR 2025-08-25 14:16:05,629 log Internal Server Error: /api/data/s2_1articles/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1193, in get_field_names
    assert field_name not in self._declared_fields, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot both declare the field 'department_name' and include it in the ReportSerializer 'exclude' option. Remove the field or, if inherited from a parent serializer, disable with `department_name = None`.
ERROR 2025-08-25 14:18:40,294 log Internal Server Error: /api/data/s2_1articles/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\serializers.py", line 1193, in get_field_names
    assert field_name not in self._declared_fields, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot both declare the field 'student_name' and include it in the ReportSerializer 'exclude' option. Remove the field or, if inherited from a parent serializer, disable with `student_name = None`.
ERROR 2025-09-06 22:22:25,636 log Internal Server Error: /api/data/t1research/download-template/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\reports\views.py", line 66, in download_template
    return generate_blank_excel_template(model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\reports\utils.py", line 114, in generate_blank_excel_template
    ws_data.conditional_formatting.add(cell_range, Rule(type="isBlank", dxf=dxf, stopIfTrue=True))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\openpyxl\formatting\rule.py", line 194, in __init__
    self.type = type
    ^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\openpyxl\descriptors\base.py", line 132, in __set__
    raise ValueError(self.__doc__)
ValueError: Value must be one of {'notContainsBlanks', 'timePeriod', 'cellIs', 'beginsWith', 'colorScale', 'dataBar', 'containsText', 'endsWith', 'top10', 'containsBlanks', 'notContainsErrors', 'iconSet', 'uniqueValues', 'aboveAverage', 'containsErrors', 'notContainsText', 'duplicateValues', 'expression'}
ERROR 2025-09-06 22:30:06,601 log Internal Server Error: /api/data/t1research/download-template/
Traceback (most recent call last):
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\reports\views.py", line 66, in download_template
    return generate_blank_excel_template(model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\reports\utils.py", line 175, in generate_blank_excel_template
    ws_data.conditional_formatting.add(cell_range, Rule(type="isBlank", dxf=dxf, stopIfTrue=True))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\openpyxl\formatting\rule.py", line 194, in __init__
    self.type = type
    ^^^^^^^^^
  File "G:\professional life\projects\Final sem project\Quarterly Report\backend\env\Lib\site-packages\openpyxl\descriptors\base.py", line 132, in __set__
    raise ValueError(self.__doc__)
ValueError: Value must be one of {'dataBar', 'uniqueValues', 'duplicateValues', 'beginsWith', 'expression', 'cellIs', 'colorScale', 'endsWith', 'containsBlanks', 'top10', 'notContainsBlanks', 'containsErrors', 'containsText', 'notContainsErrors', 'timePeriod', 'aboveAverage', 'iconSet', 'notContainsText'}
